name: Windup PR builder

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  windup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: windup/windup
      - name: Set up JDK 11
        uses: actions/checkout@v3.0.2
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
          cache: 'maven'
      - name: Build on JDK 11
        run: mvn -B clean install -DskipTests

  windup-maven-plugin:
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.0.2
    - name: Set up JDK 11
      uses: actions/setup-java@v3.3.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - name: Maven build
      run: mvn clean install -B -s build/settings.xml -Dorg.apache.maven.user-settings=build/settings.xml
